apiVersion: v1
kind: Service
metadata:
  name: manager-svc
  namespace: fibonacci
spec:
  selector:
    app: manager
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: fibonacci
spec:
  replicas: 2
  selector:
    matchLabels:
      app: manager
  template:
    metadata:
      labels:
        app: manager
    spec:
      containers:
      - name: manager
        image: golenski/fibonacci-task-manager:1.0
        resources:
          limits:
            memory: "700Mi"
        ports:
        - containerPort: 8080
        env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: fib-secret
                  key: PG_PASSWORD
          - name: BROKER_URL
            value: failover:(tcp://amq-svc:61616)?jms.useAsyncSend=true&initialReconnectDelay=1000
          - name: BROKER_USER
            value: admin
          - name: BROKER_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: fib-secret
                  key: AMQ_PASSWORD
          - name: WORKER_QUEUE_NAME
            value: worker
          - name: RESULT_LISTENER_CONCURRENCY
            value: 1-2
          - name: POSTGRES_DATASOURCE_URL
            value: jdbc:postgresql://postgres-svc:5432/task_manager
          - name: POSTGRESS_POOL_SIZE
            value: '3'
          - name: POSTGRESS_CONNECTION_TIMEOUT
            value: '10000'
          - name: FIB_ALGORITHMS
            value: ITERATIVE,RECURSIVE,BINETS,EXPONENTIAL
          - name: LOGGING_LEVEL
            value: debug
          - name: JVM_OPTS
            value: -Xms512m -Xmx512m