apiVersion: batch/v1
kind: Job
metadata:
  name: db-init-job
  namespace: fibonacci
spec:
  template:
    spec:
      containers:
        - name: db-init-task-manager
          image: golenski/db-init:1.0.0
          envFrom:
            - secretRef:
                name: postgres-secret
            - configMapRef:
                name: postgres-env
          env:
            - name: POSTGRES_DB_NAME
              value: "task_manager"
            - name: POSTGRES_DB_HOST
              value: "postgres-svc"
      restartPolicy: Never
  backoffLimit: 4