apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: fibonacci
spec:
  replicas: 3
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: golenski/fibonacci-worker:1.4.0
        resources:
          limits:
            memory: "300Mi"
        ports:
        - containerPort: 8080
        envFrom:
          - secretRef:
              name: artemis-secret
          - configMapRef:
              name: artemis-env
          - configMapRef:
              name: worker-env
          - configMapRef:
              name: redis-env
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 5
          periodSeconds: 5
          failureThreshold: 3